version = 0.1
[default.deploy.parameters]
stack_name = "lambda-invoke-model"
resolve_s3 = true
s3_prefix = "lambda-invoke-model"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
